image: barichello/godot-ci:3.2.3

stages:
  - export
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - mkdir -v -p build/windows
  - mkdir -v -p build/web

windows:
  stage: export
  script:
    - cd GodotProject
    - godot -v --export-debug "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
    - godot -s ./CopyAssetFolders.gd "--build-path build/windows"
    - test -e ../build/windows/$EXPORT_NAME.exe
    - test -e ../build/windows/options.cfg
    - test -e ../build/windows/controls.json
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  only:
      - master

web:
  stage: export
  script:
    - cd GodotProject
    - godot -v --export-debug "HTML5" ../build/web/index.html
    - test -e ../build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web
  only:
      - master

# GitLab Pages Deploy
pages:
  stage: deploy
  dependencies:
    - web
  script:
    - git fetch
    - git checkout pages
    - rm -f *.md
    - mv build/web/** ./public
  artifacts:
    paths:
      - public
  only:
    - master