image: barichello/godot-ci:latest

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  EXPORT_NAME: cudovisna-avantura

windows_dev:
  stage: export
  script:
    - mkdir -v -p build/windows_dev
    - cd godot_project
    - godot -v --export-debug "Windows Desktop Dev" ../build/windows_dev/$EXPORT_NAME.exe
    - godot -s ./CopyAssetFolders.gd "--build-path build/windows_dev"
    - test -e ../build/windows_dev/$EXPORT_NAME.exe
    - test -e ../build/windows_dev/default_options.cfg
    - test -e ../build/windows_dev/default_controls.json
    - test -e ../build/windows_dev/default_context.json
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows_dev
  only:
      - master

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - cd godot_project
    - godot -v --export-debug "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
    - test -e ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  only:
      - master

# Android Debug Job. It will use the generated debug.keystore. 
android_debug:
  stage: export
  script:
    - mkdir -v -p build/android
    - cd godot_project
    - godot -v --export-debug "Android Debug" ../build/android/$EXPORT_NAME-debug.apk
    - test -e ../build/android/$EXPORT_NAME-debug.apk
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/android
  only:
    - master

web:
  stage: export
  script:
    - mkdir -v -p build/web
    - cd godot_project
    - godot -v --export-debug "HTML5" ../build/web/index.html
    - test -e ../build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web
  only:
      - master

# GitLab Pages Deploy
pages:
  stage: deploy
  dependencies:
    - web
  script:
    - git fetch
    - git checkout pages
    - rm -f *.md
    - mv build/web/** ./public
  artifacts:
    paths:
      - public
  only:
    - master